version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    expose:
      - "5000"
    deploy:
      replicas: 3
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app

  db:
    hostname: db
    image: postgres:13
    environment:
      POSTGRES_DB: flask_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
