version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
