name: CI Workflow

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: app_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - "5432:5432"

      redis:
        image: "redis:alpine"
        ports:
          - "6379:6379"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Run Tests
      run: |
        docker-compose -f docker-compose.yml up --build --abort-on-container-exit

    - name: Shut down Docker Compose
      run: docker-compose -f docker-compose.yml down
