name: CI Workflow

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Build and Push Docker Image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        docker build -t $DOCKERHUB_USERNAME/flask-app .
        docker push $DOCKERHUB_USERNAME/flask-app:latest

  test:
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - name: Run tests
      run: docker-compose run app pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy to Server
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh user@server "docker pull $DOCKERHUB_USERNAME/flask-app:latest &&
        docker-compose up-d"
